doc/build-osx.md
Trivial: Update Mac instructions to use correct directory name.
closes #9
=> Update Mac instructions to use correct directory name.

src/rpc/misc.cpp, src/wallet/wallet.h, test/functional/p2p-versionbits-warning.py, test/functional/raven_cli.py, test/functional/rpcnamedargs.py
Added back getinfo, it was removed in Bitcoin 0.16 but most pool software still uses it.
=> Added getinfo back

src/rpc/mining.h
Disables the miner(by default, it still can be enabled), as CPU mining is no longer profitable.
=> Disable the miner in the wallet by default

README.md
When I click on the link it gives me an error that the mailing list doesn't exist.
=> Dev mailing list doesn't exist (yet?)

src/Makefile.test.include, src/assets/assets.cpp, src/assets/assets.h, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/test/assets/asset_tests.cpp, src/test/assets/asset_tx_tests.cpp, src/txmempool.cpp, src/validation.cpp, src/wallet/wallet.cpp
Because assets behave differently from RVN. Consensus rules must be added to prevent transactions that burn assets. This means that for every asset that is spent, the same amount of assets must be sent to an address. 
To compensate for the ability to not burn assets. There is a globally know burn address were you can send assets. Nothing in this address will be spendable because of the ability to not generate the private key for it.
=> Add consensus rules for asset inputs and outputs values must match

src/assets/assets.cpp, src/test/assets/asset_tests.cpp
30 max characters (excluding '!' for ownership)
unique asset tag can't contain '!'
=> Asset name validation changes for ownership '!'

src/assets/assets.cpp, src/assets/assets.h, src/rpc/assets.cpp
Currently we have a map of assets address and there balances, that never clears. Once users are using assets more this map would grow in size and require a large of memory that could crash some systems running the wallet. 
This change will make it so that the map is more of a cache, and only contains items that where changed since the last blockchain saved state. If will clear up the memory and make it so that the wallet can be run easily and not require more memory.
=> Update asset cacheing

src/assets/assets.cpp, src/assets/assets.h, src/rpc/rawtransaction.cpp, src/script/script.cpp, src/script/script.h, src/script/standard.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Added the ability to see the asset data when calling the following rpc calls. 
Here are some examples of the results
=> Added asset data to rpc call return data and fix unit tests

src/assets/assets.cpp, src/rpc/assets.cpp, src/test/assets/asset_tests.cpp, src/test/rpc_tests.cpp
Fixes raven asset names RegEx that causes build errors introduced in  #125.  Remove the reissue test from rpc_tests since it cannot be called without owner token. Fix help string that was missing optional parameter indication using ().  Add tests for invalid (reserved) raven names - RVN, RAVEN, RAVENCOIN, RAVEN.COIN, RAVEN_COIN.
=> Fix asset regex names (fixes build errors from #125)

src/assets/assets.cpp, src/test/assets/asset_tests.cpp
Modified reserved (disallowed) raven names: RVN, RAVEN, RAVENCOIN, RAVENC0IN, RAVENCO1N, and RAVENC01N.  These words can be inside or at the end a name (i.e. SERVNOT, SPYDER_RAVEN.)
=> MNEY - change reserved raven names

assets/asset_metadata_spec.md
Figure it's better to be associated with the OG Bitcoin. Or a good alternative example may be Ethereum/ETH or Monero/XMR.
=> Changed name/symbol example to Bitcoin/BTC

src/qt/assetsdialog.cpp, src/qt/assetsdialog.h, src/qt/forms/assetsdialog.ui
Added the ability to click a button to generate a new block while running the wallet on regtest. This should significantly reduce testing time as the user doesn't have to use the debug console anymore to generate blocks using generate *int*
=> Add regtest mining shortcut to assets tab

src/assets/assets.cpp
Initially, when I added the asset name validation regex to exclude variations of RAVEN I removed the end delimiter '$' as things worked fine without it.  For better compatibility, this is being added back.
=> MNEY - add $ to end of regex for better compatability

src/rpc/assets.cpp
Changes the descriptors to the standard "numeric" which is used to denote either Float or Integer in the rest of the codebase, as issue and reissue and transfer all accept non integer values
=> Update Asset RPC man

doc/release-notes/release-notes-2.0.4.md
=> Add 2.0.4 release notes

src/assets/assetdb.cpp, src/assets/assetdb.h, src/assets/assets.cpp, src/assets/assets.h, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/init.cpp, src/test/assets/asset_tx_tests.cpp, src/txmempool.cpp, src/validation.cpp, test/functional/assets.py
Because reissue transaction require a state based check from memory or database to verify the validity of the reissue transaction. Only one reissue transaction can be made per asset until the transaction is accepted into a block. 
If a transaction doesn't contain a necessary fee to get accepted into a block, the owner of the asset will have to wait until the transaction is removed/expires from the mempool to be able to reissue the asset again.
=> Remove the ability to chain reissue transactions

src/assets/assets.cpp, src/assets/assets.h, src/consensus/tx_verify.cpp, src/test/assets/asset_tx_tests.cpp
- Move unit checking to own method
- Create unit test for checking units
- Add unit checking to asset issuance
- Update reissue and transfer unit checking to use unit checking method
=> Check units when issuing assets

src/consensus/tx_verify.h
Not sure why this builds fine on OS-X.  Should be failing to build there too.  Simple one-line change to include string...
=> Fixing Linux build errror - missing string include in header

src/assets/assettypes.h, src/rpc/assets.cpp
A recent change broke the Linux build process.  This PR resolves that issue.
=> Fixing Linux compile-linker error

src/assets/assets.cpp, src/qt/transactionrecord.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h
Normal RVN transactions were not showing the change outputs in the transaction page. They do this by creating change address and not adding them to the wallet. Asset change addresses where not being created the same way and because of that they were spamming the transaction list on the GUI. This made the GUI messy. 
This changes makes it so asset change addresses are created like normal RVN transactions. This also fixes a bug where ownership assets weren't showing up in the GUI correctly.
=> Hide asset change addresses

src/validation.h
Default RBF (BIP125) to off.
Advantage: Works like Bitcoin prior to ver 12 when 0 conf was accepted for low dollar items.  Increases difficulty of undoing a 0 conf transaction.
=> Default RBF to off

test/functional/wallet_bumpfee.py, test/functional/wallet_listtransactions.py
The wallet_bumpfree.py and wallet_listtransactions.py tests both needed to be modified to reflect the change [PR-286](https://github.com/RavenProject/Ravencoin/pull/286).
=> modifying functional tests to reflect the recent RBF change

src/chainparams.cpp, src/chainparams.h, src/consensus/validation.h, src/init.cpp, src/net_processing.cpp, src/validation.cpp
This allows clients to run the wallet and not allow reorganizations that are 55 or more blocks. This can be changed on client start by passing in the flag `maxreorg=<n>`
This should help stop potential chain attacks by malicious users as well as allow exchanges to augment the required amount of confirmations required.
=> Add Max Reorganization Depth

src/assets/assetdb.cpp, src/assets/assetdb.h, src/assets/assets.cpp, src/assets/assets.h, src/assets/assettypes.h, src/coins.cpp, src/coins.h, src/qt/forms/reissueassetdialog.ui, src/qt/reissueassetdialog.cpp, src/qt/reissueassetdialog.h, src/rpc/assets.cpp, src/rpc/client.cpp, src/test/assets/asset_reissue_tests.cpp, src/test/assets/serialization_tests.cpp, src/validation.cpp, src/validation.h
Now, when you reissue an asset. You can change the units assigned to that asset. You can only make the units larger/more precise 
**Unit from 0 -> 1**
`e.g.  1 -> 1.0` Valid Unit Change
**Unit from 0 -> 2**
`e.g. 1 -> 1.00` Valid Unit Change
**Unit from 1 -> 0**
`e.g. 1.0 -> 1` Not Valid
=> Add units to reissuable data

src/assets/assets.cpp, src/qt/createassetdialog.cpp, src/qt/createassetdialog.h
Fixes #281 found by @Scotty0448 
At a consensus level the unique asset metadata wasn't being validated. 
This PR adds checks to make sure the Units are set to 0 and the Amount is set to 1 * COIN.
Also, the QT wallet now sets these values for you if you try to create a Unique Asset using the asset creation prompt.
=> Add Unique isValid consesus checks

test/functional/test_runner.py
Many of the extended tests run quickly now, so there is no reason for them to be in the extended tests.  Also commented out the failing tests for now.
=> Move extended tests

test/functional/rpc_invalidateblock.py, test/functional/wallet_txn_clone.py
Since these two tests were in the extended, and now in the base functional tests we missed the max-reorg depth change that also needed to be applied to allow these tests to run correctly.
=> Fixing two additional tests that needed updates for the new max-reorg

src/assets/assets.cpp, src/assets/assettypes.h, src/rpc/assets.cpp, src/test/assets/serialization_tests.cpp, test/functional/feature_assets.py, test/functional/feature_rawassettransactions.py
The purpose here is to get close enough to the KAAAW protocol to allow for future expansion without protocol changes.
=>  changes to script serialization of IPFS hash for issue/reissue

doc/release-notes-pr12924.md, src/key.cpp, src/key.h, src/test/bip32_tests.cpp, src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.h, test/functional/keypool.py, test/functional/wallet-dump.py, test/functional/wallet-hd.py
This is a revision of #165 requested by Roshi
This backports https://github.com/bitcoin/bitcoin/pull/12924 to our current implementation of the RPC-API
6249021d1 [docs] Add release notes for HD master key -> HD seed
rename (John Newbery)
79053a5f2 [rpc] [wallet] Add 'hdmasterkeyid' alias return values. (John Newbery)
c75c35141 [refactor] manually change remaining instances of master key to seed. (John Newbery)
131d4450b scripted-diff: Rename master key to seed (John Newbery)
Pull request description:
This renames a couple of functions and members (no functional changes, expect log prints):
- Rename CKey::SetMaster to CKey::SetSeed
- Rename CHDChain::masterKeyId to CHDChain::seedID
- Rename CHDChain::hdMasterKeyID to CHDChain::hdSeedID
- Rename CWallet::SetHDMasterKey to CWallet::SetHDSeed …
=> [BACKPORT] #12924: Fix hdmaster-key / seed-key confusion (scripted diff)

doc/build-osx.md
Just adding information about the known seg-fault issue to the OSX-Build documentation.
=> Adding warning about Mojave build

src/rpc/assets.cpp
The issueuniqe command help was a little unclear on how to actually invoke it.  It requires using single quotes (') around the array in order to be called.  This isn't listed in the help message.  This only updates the help to include the single quote around the arrays.
=> Make 'issueunique' cli-help message more clear

src/assets/assets.cpp, src/assets/assets.h, src/assets/assettypes.h, src/coins.cpp, src/consensus/tx_verify.cpp, src/qt/assetcontroldialog.cpp, src/qt/assettablemodel.cpp, src/qt/createassetdialog.cpp, src/qt/reissueassetdialog.cpp, src/qt/sendassetsentry.cpp, src/qt/transactiondesc.cpp, src/qt/transactionrecord.cpp, src/rpc/assets.cpp, src/test/assets/asset_reissue_tests.cpp
- The asset wallet balance will now show the selected total from asset control. 
- The asset wallet balance will now show total of wallet asset balance, not what is in the cache
- Updated when assets show up the transfer asset dropdown (The asset shows up if the assets issuance is in the cache/database)
- Renamed GetAssetIfExists to GetAssetMetaDataIfExists because we are really retrieving the metadata from the cache or database and not so much the Asset.
=> Update wallet balance and transfer GUI

src/qt/assetsdialog.cpp, src/qt/assetsdialog.h, src/qt/createassetdialog.cpp, src/qt/forms/createassetdialog.ui, src/qt/forms/optionsdialog.ui, src/qt/forms/reissueassetdialog.ui, src/qt/optionsdialog.cpp, src/qt/optionsmodel.cpp, src/qt/optionsmodel.h, src/qt/reissueassetdialog.cpp
- Update the size of the createassetdialog, and reissueassetdialog (Made them smaller)
- Added a setting that allows you to turn on custom fee on the asset tabs 
- You can turn this on by navigating to the settings and enabling it. Just like coin control
P.S. This doesn't remove the custom fee from the send RVN page. That is always active
=> Add custom fee as a setting that can be turned off/on

src/qt/forms/overviewpage.ui, src/qt/overviewpage.cpp
- Allow asset list to go to the bottom of the page ( Used to go to the middle of the page)
**_Before_**
**_After_**
=> Extend asset list to the bottom of the screen

src/assets/assets.cpp, src/assets/assets.h, src/qt/createassetdialog.cpp, src/qt/createassetdialog.h, src/qt/reissueassetdialog.cpp, src/qt/reissueassetdialog.h, src/rpc/assets.cpp
- Added checks to ipfs hash when user is inputed text, now it will let the user know at all stages what is the issue with the ipfs hash
- Added the ability to check the ipfs checkbox and not input ipfs hash and still create or reissue assets
- Added additional ipfs validity checks
- Added some translation code to some string that will be printed out to users
=> Check ipfs validity in GUI, and rpc call

doc/README_windows.txt
In testing Windows build stuffs today I noticed the link to the RVN wiki was incorrect in the Windows readme file.
=> Fixing link in Windows readme to the Ravencoin wiki page

src/assets/assets.cpp, src/assets/assets.h
- The ability to create the same unique asset and submit it to the mempool was allowed. 
- Now, during the mempool check we make sure to check if it is already in the mempool or not and fail it is it.
=> Fail checks on unique asset that are already in the mempool

src/qt/createassetdialog.cpp, src/qt/forms/reissueassetdialog.ui, src/qt/reissueassetdialog.cpp
- Sometimes when the mange assets or create assets was opened, the window was really large, this change should help resize the window to the contents of the screen. 
- When coin control and custom fee are turned on, the manage assets window is pretty large. But this should resize based on the monitor it is on.
=> Resize asset dialog when opened to fix contents

doc/fuzzing.md, doc/release-notes/release-notes-2.1.0.md, test/functional/test_runner.py, test/functional/wallet_listtransactions.py
Release notes for 2.1.0.
Fixing functional tests that recently began to fail due to the removal of RBF
Fixing link for fuzz testing input file (using Bitcoin file)
=> Adding release notes for 2.1.0, removing RBF tests

src/assets/assets.cpp, src/txmempool.cpp, src/txmempool.h, src/validation.cpp, test/functional/feature_assets_mempool.py
- Remove heavy mempool check which was looping through the whole mempool to see if asset is unique. 
- Remove assets from map when that asset is added into a block
This fixes the case where a miners mempool can get into a state where it produces invalid block templates which will produce invalid blocks because it contains transactions which contain issuances which have already been mined.
=> Add ability to view asset issuance in the mempool

doc/release-notes/release-notes-2.1.0.md
Activates Oct 31, note 30, and change version from 2.1.0.0 to 2.1.0
=> fixing asset activation date and remove extra 0 from version

src/init.cpp
Resolves issue https://github.com/RavenProject/Ravencoin/issues/313
Help message for ravend crashed during a call to get the blockmaxweight which in turn used AreAssetsDeployed.  This used consensus params that were not yet initialized since raven was not running.  Now, this just returns the pre RIP2 block weight.
=> Fixing crash when running 'ravend -h'

test/functional/feature_assets_mempool.py
- Add functional test which tests the mempool is in a valid state after an asset issuance is reorged
=> Add functional test for mempool cleaning up after reorg

src/chainparams.cpp
The MIT License states "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." Removing Bitcoin Core's reference violates that.
=> Add bitcoincore's license line back

contrib/macdeploy/macdeployqtplus
Cross-compiling OSX version of RVN in Docker was failing to compile when it was trying to find the dynamic library version of libboost_system-mt.dylib.  RVN is compiled as static so this dynamic library isn't needed.  Verified using the Docker image for release building and manually on a standalone AWS Linux machine.  Tested on a "clean" (non-development configured) Macbook.
=> Fixing OSX cross compile build problem on Linux (static build pulling dynamic Boost library)

src/qt/assettablemodel.cpp
fixing build error on Linux:
`qt/assettablemodel.cpp: In member function ‘virtual QVariant AssetTableModel::data(const QModelIndex&, int) const’:
qt/assettablemodel.cpp:145:25: error: conversion from ‘CAmount {aka long int}’ to ‘QVariant’ is ambiguous
return rec->quantity;
^~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:43:0,
from /usr/include/x86_64-linux-gnu/qt5/QtCore/QAbstractTableModel:1,
from qt/assettablemodel.h:11,
from qt/assettablemodel.cpp:6:`
=> Fixing build on Linux due to Long Int conversion error

src/Makefile.qt.include
missing .h file in the qtmakefile includes caused the file to be missing from source tarballs
=> Fix Tarball Builds

src/qt/assetsdialog.cpp, src/qt/createassetdialog.cpp, src/qt/forms/reissueassetdialog.ui, src/qt/guiconstants.h, src/qt/overviewpage.cpp, src/qt/ravengui.cpp, src/qt/receivecoinsdialog.cpp, src/qt/reissueassetdialog.cpp, src/qt/sendassetsentry.cpp, src/qt/sendcoinsdialog.cpp, src/qt/sendcoinsentry.cpp
- Make QT reissue default to amount of 0 instead of 1
- Update the shadow color of the wallet frame
- Update the shadow color of light mode wallet cards
- Moved color string into constants file
=> Update GUI with reissue quantity of 0 by default

build-aux/m4/ac_compare_version.m4, build-aux/m4/ax_compiler_vendor.m4, build-aux/m4/ax_compiler_version.m4, configure.ac
A while back to avoid getting multiple issues submitted a week due to Linux compile failures we modified it so that all Linux builds would compile with the -fPIC flag.  This was always meant as a temporary fix.  This change now checks the GCC version and sets the -fPIC flag if it is one of the older compiler versions that will fail without -fPIC.  I verified on as many Linux distros as I had access to that versions 5.x and 6.x will both fail to compile without -fPIC.  GCC versions 7.3.0 and newer appear to work without error.  This change supersedes PR #207
=> Only set fPIC on compilers that need it

doc/build-windows.md
In order to complete windows builds NSIS is used to package up the installer, but it wasn't in the instructions.  Now it is.
=> Adding missing NSIS dependency to build instructions

src/wallet/wallet.cpp, test/functional/feature_rawassettransactions.py, test/functional/rpc_fundrawtransaction.py
SelectCoins explicitly failed if any provided input wasn't a wallet output.  Lifting this to allow fundrawtransaction to work with non-wallet outputs.
=> Allowing non-wallet inputs in fundrawtransaction.

assets/tools/asset_audit.py, test/functional/test_runner.py
issue #506 
The asset audit script did not include information for running main-net auditing, also the testnet and regtest port numbers were incorrect.  It also did not contain information about needing the bitcoin-rpc python-pip library to be able to run.  These are all now included. 
The functional test was still randomly failing certain tests.  I've found that if you run the tests with only one thread (default is 4) that the tests almost always run successfully.  It takes much longer with only 1 test running at a time, so as a compromise I've set it to only use 2-threads by default.  This can be overridden on the command line using the -j=n or --jobs=n.  An occasional false negative failure will still occur, but it is much less frequent - about 1.5 out of 10 times running the full …
=> Minor test fixes for asset_audit and functional test runner

src/primitives/transaction.cpp
A recent change caused the OSX compile to fail with a linker error.  Since the log print line isn't needed this is the easy way to resolve this error.
=> Fixing OSX build / link error

src/qt/reissueassetdialog.cpp
- Managed assets weren't showing up after they were mined in the qt list of assets. 
- Clicking the clear button will now reset the list to include all newly mined coins
=> Allow clear to update reissue asset list

test/functional/feature_assets.py, test/functional/feature_rawassettransactions.py
Both of these tests were failing due to recent changes in the RPC error messages that were being returned. The text of the expected PRC error was changed in the tests to reflect the changes made in the code.
=> Fixing two of the functional - asset feature tests

src/rpc/messages.cpp
- Allow the input of normal Root and Sub Asset name, and convert them to owner tokens
- Update rpc error messages
=> Update messaging rpc calls

src/init.cpp, src/init.h, src/net.cpp, src/net.h, src/qt/forms/debugwindow.ui, src/qt/raven.cpp, src/qt/ravengui.cpp, src/qt/ravengui.h, src/qt/rpcconsole.cpp, src/qt/rpcconsole.h
This adds a Wallet Repair tab to the debug window. It also adds a Wallet Repair menu item to the Help menu. The general functionality was extracted from a similar implementation in Dash.
The repairs are accomplished by automatically restarting Raven Core with one of three options: rescan, zapwallettxes=1 or reindex.
=> Add Wallet Repair tab to the debug window

src/assets/assets.cpp
In older testnet builds, users were able to set the reissuable value with values that aren't 0 or 1. This means that the software must take this into account when syncing the chain. This change, fixes sync issues on the testnet chain, and allows nodes to fully sync with no problems
=> Fix testnet reissue sync

src/versionbits.cpp
In Ravencoin, we increment our block versions by 1 when a new RIP is activated.
This change broke versionbit checking because it was using VERSIONBITS_TOP_BITS for the initial block version. 
This change removes that initial check and just checks the bits in the version to see if they are voting yes or no.
=> Update version bit checking to not look for initialblock version

src/assets/assets.cpp, src/assets/assets.h, src/rpc/assets.cpp, src/rpc/client.cpp, src/rpc/rawtransaction.cpp, src/test/assets/asset_tests.cpp, src/test/assets/verifier_string_tests.cpp, src/wallet/coincontrol.h, src/wallet/wallet.cpp, test/functional/rpc_assettransfer.py, test/functional/test_runner.py
- Add ability to specify a asset change address as well as a raven change address in the transfer rpc calls
- Allow users to use the console commands without having to add the special characters for qualifier and restricted assets. (#,$)
- Add functional tests to verify that the asset change support works correctly
- Updated units to work with the special character changes
=> Asset change support and smart type checking

src/version.h, test/functional/test_framework/mininode.py
The MIN_PEER_PROTO_VERSION was recently changed from using GETHEADERS_VERSION=31800 to using ASSETDATA_VERSION=700017.  This change fixes the tests to use the new version number. Also added a note version.h so future changes will hopefully remember to also update the test version to match.
=> Fix functional tests failing on verack

test/functional/feature_unique_assets.py
Noticed today that the test/functional/feature_unique_assets.py script could generate an invalid asset.  The array used to create random asset names included the forward-slash (\) and was missing the dash (-).  This would cause the test to randomly fail.
=> Unique Assets Functional Test Could Use Invalid Character

depends/packages/packages.mk, depends/packages/qt.mk
Because.... it works? 😄 
```
cd depends
make HOST=arm-linux-gnueabihf -j4
cd ..
./autogen.sh
./configure --prefix=$PWD/depends/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++
make
```
=> Backport of Bitcoin Core PR13604 and PR13750 to add 32-bit arm support for Raven-qt

src/assets/assets.cpp, src/assets/assets.h, src/assets/messages.cpp, src/assets/messages.h, src/coins.cpp, src/init.cpp, src/miner.cpp, src/qt/assettablemodel.cpp, src/qt/ravengui.cpp, src/qt/rpcconsole.cpp, src/qt/rpcconsole.h, src/qt/walletview.h, src/rpc/assets.cpp, src/rpc/messages.cpp
With these changes you can now configure the raven coin daemon to not use a wallet. 
./configure --disable-wallet
=> Add support to run with disable-wallet

src/qt/forms/restrictedassignqualifier.ui, src/qt/forms/restrictedfreezeaddress.ui, src/qt/restrictedassetsdialog.cpp, src/qt/restrictedassignqualifier.cpp, src/qt/restrictedassignqualifier.h, src/qt/restrictedfreezeaddress.cpp, src/qt/restrictedfreezeaddress.h, src/rpc/assets.cpp
- updated rpc calls to allow asset data to be added to the transaction
- update gui to allow for asset data to be added to the transaction
=> Add ability to attach asset data to tag/freeze transactions

src/Makefile.am, src/Makefile.qt.include, src/assets/assets.cpp, src/assets/assets.h, src/assets/messages.cpp, src/assets/myassetsdb.cpp, src/assets/myassetsdb.h, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/init.cpp, src/qt/forms/restrictedassetsdialog.ui, src/qt/myrestrictedassetrecord.cpp, src/qt/myrestrictedassetrecord.h, src/qt/myrestrictedassettablemodel.cpp, src/qt/myrestrictedassettablemodel.h, src/qt/restrictedassetsdialog.cpp, src/qt/restrictedassetsdialog.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h, src/rpc/messages.cpp, src/validation.cpp, src/validation.h, src/wallet/wallet.cpp, src/wallet/wallet.h
- Add rpc call to view wallets tagged addresses
- Add rpc call to view wallets restricted addresses
- Added backend database to support wallet tagged and restricted addresses
- Added QT Table model to display when addresses are tagged or restricted
=> Add support for wallets restricted address DB/Qt

test/functional/feature_assets_mempool.py, test/functional/feature_rawassettransactions.py, test/functional/test_framework/authproxy.py, test/functional/test_runner.py, test/functional/wallet_basic.py
- feature_assets_mempool.py - Intermittent failure because chain sync sometimes didn't finish in time, uses new functionality that waits for chans to sync before checking.
- feature_rawassettransactions.py - Intermittent failure, used same UTXO which would occasionally run out of funds and create transactions with negative values.  Now it checks and retrieves the first UTXO with a large enough balance.
- authproxy.py - Added an exception handler for unknown protocol, resolves a few intermittent failures.
- test_runner.py and wallet_basic.py - Last year I accidentally removed this test from the list of tests to run.  It was also broken due to fee changes and how RVN handles long chains in the mempool.  Also found an issue that is a bug on Bitcoin main in this test where the nodes are …
=> Fixing a few small test issues

test/functional/feature_assets_reorg.py, test/functional/feature_dbcrash.py, test/functional/interface_raven_cli.py, test/functional/rpc_net.py, test/functional/test_framework/test_framework.py, test/functional/test_framework/test_node.py, test/functional/test_runner.py, test/functional/wallet_basic.py
This PR adds some new functionality to the test runner.  It also speeds the running of the tests up (previously we slowed them down to help them run more consistently). It does this by getting the CPU count from the OS and running the same number of test threads simultaneously. 
The test results are now sorted so passed tests are at the top, failed at the bottom.  Passed tests are marked in green and failed tests in red.
A new command argument was added --FailFast.  If this flag is set the test runner will abort on the first test failure instead of continuing.
A second new argument was added --filter='regex, filter list'.  This uses regular expressions to allow the test runner to only run specific tests
The test runner display results is more compact than before. The dots indicating test …
=> Functional test cleanup, stabilization, optimization, beautification

src/qt/platformstyle.cpp, src/qt/platformstyle.h, src/qt/transactiontablemodel.cpp, src/qt/transactiontablemodel.h
The Qt wallet transaction history uses 'RVN' for all RVN transactions even if a different display unit is chosen in the options. This has occasionally been a cause of confusion for some users.
These changes:
* Use the correct unit (e.g. RVN, mRVN or μRVN) in the transaction history 'Asset' column and recent transactions
* Removes display unit from the 'Amount' column (as asset amounts are not in RVN)
* Further reduces potential for confusion by displaying asset names in a different colour (I chose raven blue)
=> Display correct unit in Qt wallet transaction history

test/functional/feature_restricted_assets.py, test/functional/test_framework/test_framework.py
Fixing restricted asset test - it was previously valid to freeze and unfreeze multiple times in one. As of PR #704 this is no longer the case.  Now the tests freezes once, and expects assertion on the second attempt.
Also found a problem in the test runner --loop argument. If a test during an early loop fails, it will fail every loop afterwards - This is because the directory structure is not deleted when a test fails (to allow looking at logs etc). The options were to override the directory (would lose any debug info), or to create a new directory - this is what it now does.  The test now simply appends a  "random" integer to the end of the pathname. This will allow for tests to continue to run with or without error as desired.
=> Fixing broken restricted asset test and loop argument

test/functional/interface_rpc.py, test/functional/test_framework/authproxy.py, test/functional/test_runner.py
Add interface_rpc.py test from BTC
=> Add interface_rpc.py test from BTC

src/assets/assets.cpp, src/consensus/tx_verify.cpp, src/script/script.cpp
If a script is above a certain size, the RVN characters are placed in different indexes in the script. This change makes sure that all scripts that might be asset scripts meet the size constraints for finding all required asset special characters.
=> Fix script size check by gu3

src/chainparams.cpp, test/functional/rpc_decodescript.py
- Added time to start RIP5 voting on mainnet
- Made the voting activation 85% on mainnet
- Updated minimum chain work to block 1040000
- Updated valid signature check to block 1040000
- Fix functional test using asm asset decoder
=> [Consensus] Add restricted assets activation vote time

test/functional/feature_uacomment.py
Simple fix, change the expected string to match what is now returned 286 vs 288,
=> fixing the feature_uacomment.py test

test/functional/feature_restricted_assets.py
Feature_restricted_asset.py test was failing in a few steps where the transaction had already been added to the mempool.
=> Fixing tx already in mempool errors in restricted asset test

src/blockencodings.cpp, src/chainparams.cpp, src/crypto/ethash/include/ethash/progpow.hpp, src/crypto/ethash/lib/ethash/progpow.cpp, src/hash.cpp, src/hash.h, src/miner.cpp, src/net_processing.cpp, src/primitives/block.cpp, src/primitives/block.h, src/rpc/blockchain.cpp, src/rpc/mining.cpp, src/test/test_raven.cpp, src/validation.cpp
Because we use block.GetHash() everywhere in the code to obtain the block hash. We are currently triggering it to do a full kawpow hash. Which when done on the same block multiple times can really slow down the syncing process. 
This commit changes to only do the full KawPow hash when checking the ProofofWork. If the proof of work is correct then we know we have a valid block. 
Everywhere else the GetHash is called for `logging`, `qt gui updates` we want to use the light mix_hash varient which doesn't take much time to compute at all.
=> Only do full kawpow hash when checking POW

src/wallet/rpcdump.cpp, src/wallet/rpcwallet.cpp
- Added masterpubkey to dumpwallet rpc call
- Added new rpc call `getmasterkeyinfo` which returns the master public and private key (only works if wallet is unlocked)
=> Add new call to get masterpubkey easily

src/qt/assetsdialog.cpp, src/qt/sendassetsentry.cpp
- Found bug where the wrong message box text was being grabbed. 
- Added message to the asset transfer
=> Fix memo's not attaching to GUI asset transfers

src/chainparams.cpp, src/consensus/consensus.h, src/consensus/params.h, src/consensus/tx_verify.cpp, src/consensus/tx_verify.h, src/qt/ravengui.cpp, src/rpc/blockchain.cpp, src/rpc/blockchain.h, src/test/assets/asset_tx_tests.cpp, src/validation.cpp, src/validation.h, src/version.h, src/versionbits.cpp
- Added Bip Logic for the new ENFORCE_VALUE BIP which will enforce reissue assets to have a value of 0 in the txout.nValue - 62c30f9, 905952c, 787d4c0, 9c8fbc0, 8141607, c455cfc, 185a052, 09578af   
- Added new rpccall `decodeblock` - ae65a29
- Updated GUI version checking to use configure.ac variable -  8c1fb71, 627a6f0, 405e1ee
Code Added by developers:
@akshaynexus - 8c1fb71 
@blondfrogs - 62c30f9, 905952c, 787d4c0, 9c8fbc0, 8141607, c455cfc, 185a052, 09578af, 627a6f0, 405e1ee, ae65a29, e889065
Closes #795
=> Update develop with enforced value fixes

src/init.cpp, src/qt/clientmodel.cpp, src/qt/myrestrictedassettablemodel.cpp, src/qt/overviewpage.cpp, src/qt/ravengui.cpp, src/qt/splashscreen.cpp, src/qt/trafficgraphwidget.cpp, src/qt/transactiontablemodel.cpp, src/qt/walletmodel.cpp, src/rpc/server.cpp, src/scheduler.cpp, src/test/scheduler_tests.cpp, src/torcontrol.cpp, src/validation.cpp, src/validationinterface.cpp
Splitting a few changes up to simplify commits.  Part one is to resolve compile errors using boost v1.73.  Part two is resolving compile issues for QT 5.15. Part three has new test enhancements and coverage.
=> fixing boost 1.73 compile errors

.github/workflows/build-raven.yml
Previously only develop and release branches were setup to auto-build on a PR. Now this includes master.
=> Adding master branch PRs to run build as part of process

src/rpc/assets.cpp, test/functional/feature_sweep.py, test/functional/test_runner.py
Closes #880 
This commit adds the ability to sweep an address for any and all
assets given a private key and an (optional) asset filter.
`sweep privkey (asset_name)`
The default is to sweep all assets, using the RVN hosted at the
swept account to pay all network fees. If the amount of RVN is
insufficient, then the remaining fee is paid by the balance
of the receiving wallet.
This feature can be tested by running `test/functional/feature_sweep.py`
or by runnning the entire `test_runner` testing framework.
My wallet address is RHijQLBub9HYLa5kD4nzXgUzXVd23tcwEi and I look forward to your review!
=> Add sweep support to RPC

src/qt/overviewpage.cpp, src/qt/overviewpage.h
Add "Copy hash" option to the context menu in the overview page.
This is for assets with IPFS-hash attached.
=> GUI: Overview page -  copy hash context menu for IPFS hashes.

src/init.cpp
CLI/Options: Add helpmessage for -assetindex (PR #925)
Changed logging to not say error when there is no error.
=> CLI/Options: Add helpmessage for -assetindex

src/qt/guiconstants.h, src/qt/platformstyle.cpp, src/qt/sendassetsentry.cpp
GUI: Transfer Assets view - Amount-field.
- Set units from asset-units.
- Set always default to 0 when switching asset.
- Clicking arrows in the amount-field has better stepvalues.
GUI: Send and Transfer Assets
- Make a define for the hardcoded background color in send entries.
- Change the background color to match the rest.
=> GUI: Transfer assets and send view fixes (PR #927)

src/qt/forms/overviewpage.ui, src/qt/overviewpage.cpp
Made this for my own testing.
Take it if you like it.
I find that I have the wallet window bigger, and 8 recent transactions is more useful than an empty space.
=> GUI: Overview, increase size of recent transaction, now showing 8 (PR #930)

.github/workflows/build-raven.yml
Enable github caching of depends.
The depends system will rebuild depends when needed.
Speed up most builds by about 30min.
=> Build: Cache depends.

depends/packages/packages.mk
- libX11
- xextproto
- libXext
- xtrans
I have not found any reason to keep them around.
Please check for regressions.
=> Depends: Remove depends we don't need.

.github/scripts/00-install-deps.sh, .github/workflows/build-raven.yml
This addresses the issue with incompatible GLIBC versions.
Binaries built on ubuntu 20.04 does not run on 18.04 out of the box.
Building linux binaries on ubuntu 18.04 makes binaries that work on ubuntu versions 18.04, 20.04 to 21.04.
And probably most other modern distros.
This change also reduces our exposure to this issue:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189
Refs:
bitcoin#20005
bitcoin#21454
Any feedback is of course welcome.
=> Build: Switch to building on ubuntu 18.04 bionic

src/qt/guiconstants.h
Match blue and orange to the Ravencoin logo.
Closes issue #952
Co-authored-by: Michael Fussco <michael.r.fusco@gmail.com>
New colors on the left.
=> GUI: Adjust blue and orange to match the logo.

depends/packages/boost.mk
- This change was overwritten by PR 922.
=> Depends: Update boost download url (PR #972)

src/qt/overviewpage.cpp
Extra question if you really want to open IPFS-url.
Only activated on left-clicking the asset in the overview-page.
Words?
=> GUI: Warning when opening IPFS-urls. (PR #978)

src/qt/addresstablemodel.cpp, src/qt/assetsdialog.cpp, src/qt/bantablemodel.cpp, src/qt/createassetdialog.cpp, src/qt/guiutil.cpp, src/qt/guiutil.h, src/qt/optionsmodel.cpp, src/qt/overviewpage.cpp, src/qt/paymentserver.cpp, src/qt/peertablemodel.cpp, src/qt/raven.cpp, src/qt/ravenamountfield.cpp, src/qt/ravengui.h, src/qt/receiverequestdialog.cpp, src/qt/reissueassetdialog.cpp, src/qt/rpcconsole.cpp, src/qt/rpcconsole.h, src/qt/sendcoinsdialog.cpp, src/qt/splashscreen.cpp, src/qt/splashscreen.h, src/qt/transactiontablemodel.cpp, src/qt/transactionview.cpp, src/qt/utilitydialog.h
This PR removes most of the build warnings when building on Ubuntu 21.04 with Qt 5.15.2 and gcc/g++ 10.3.0.
Most of the changes are backports from bitcoin, with some adjustments.
=> qt, refactor: remove build warnings Qt 5.15.x

build-aux/m4/ax_cxx_compile_stdcxx.m4, configure.ac, src/net_processing.cpp
Update configure.ac to c++17
Update ax_cxx_compile_stdcxx.m4 from bitcoin
Copied from bitcoin master branch.
Use C++11 member initializer in CNodeState
Manually copied/adapted from bitcoin#21370
net_processing:
IteratorComparator add const. [c++17]
=> Enable and require C++17

configure.ac
Ref: CVE-2017-8798
bitcoin#10414
bitcoin#15993
configure-checks for miniupnpc API >=10.
This commit does not include the compile-time checks from bitcoin#15993.
=> Require miniupnpc v10

depends/packages/expat.mk, doc/dependencies.md
Expat renamed files on sourceforge because of CVE-2013-0340/CWE-776.
This switches to v.2.4.1.
Source changed from sourceforge to github.
=> build: update Expat 2.4.1 change source to github.

src/qt/ravengui.cpp
Code segment moved to match the order it appears
Switched alt-<num> hotkeys to match the correct order.
Set hotkey for Restricted assets (ALT+8).
=> gui: toolbar move code to match order in toolbar

src/net.cpp
p2p: add fixed seeds if less than 5 addresses available after 60 sec.
=> p2p: add fixed seeds if less than 5 addresses available after 60 sec.

src/consensus/tx_verify.cpp, src/script/script.cpp, src/script/script.h
correct verification of transactions pre p2sh-asset activation
=> consensus: correct verification of transactions pre p2sh-asset activation

src/init.cpp
Currently, the chains reject nonstandard transactions according to=> mainnet:true, testnet:false, regtest:false
The "-acceptnonstdtxn" CLI switch option is broken and has no effect.
After this simple code change, all chains default to rejecting nonstandard transactions, while allowing the "-acceptnonstdtxn" switch to change that behavior on testnet and regtest (but not mainnet).
Note that bitcoin has also fixed the "-acceptnonstdtxn" switch in their PR#15891, but in a more complicated way and with different results.
=> Fix handling of nonstandard txns and "-acceptnonstdtxn"

src/qt/reissueassetdialog.cpp
Disable units spinbox if max units is already set.
Set minvalue for spinbox after setting value, to allow
updates when the number of units in the selected asset is
lower than the number of units in the previous.
Related to issue #1045
=> GUI: Reissue asset spinboxes. Disable if unit is max.

src/random.h, src/test/random_tests.cpp, src/wallet/wallet.cpp
Backport part of bitcoin#14624
bitcoin#3db746beb407f7cdd9cd6a605a195bef1254b4c0
random_shuffle is depratected in c++17.
Fixes compile errors on freebsd and osx.
=> Introduce a Shuffle for FastRandomContext and use it in wallet

src/net.h
It does not make sense to force dns seeds by default.
=> net: Do not force dns seeds by default.

.github/workflows/build-raven.yml
Setup Skip Duplicate Actions in the workflow.
The reason for doing this, is that githubs path-ignore feature
does not play well with required checks on master.
Skip Duplicate Actions include a better paths_ignore feature.
https://github.com/marketplace/actions/skip-duplicate-actions
This should work around the unnecessary building for doc changes and similar trivial non code changes.
While still reporting the checks as successfull.
Demo result of skipped run: 
https://github.com/fdoving/Ravencoin/pull/13/checks?check_run_id=2851996052
=> build: github action enable Skip Duplicate Actions.

src/qt/forms/overviewpage.ui, src/qt/forms/reissueassetdialog.ui, src/qt/raven.cpp
Set minimum to 875x700, even that is only usable if
The toolbar is set to icons only.
Set some minimum values for layouts in overview and manage assets.
=> gui: set window minimum size to usable default

src/support/lockedpool.cpp
Manual backport of bitcoin PR#18443 and bitcoin PR#15633.
Use madvise on Linux and FreeBSD to avoid sensitive data from secure_allocator to be writte to swap and core-files.
Fixes #1117 
https://github.com/bitcoin/bitcoin/pull/15600/commits/d831831822885717e9841f1ff67c19add566fa45
https://github.com/bitcoin/bitcoin/pull/18443/commits/f85203097f78d9daa1d35c4097a80beab31da2a4
=> lockedpool: avoid sensitive data in core files (Linux and FreeBSD)

src/qt/raven.cpp, src/qt/test/test_main.cpp
Fixes issue #1110 - CVE-2021-3401
Backport of https://github.com/bitcoin/bitcoin/commit/a2714a5c
Exact same solution as: https://github.com/dogecoin/dogecoin/pull/2666
Fix is tested on Linux.
=> Dummy arguments for QApplication

src/qt/walletview.cpp
Messasgebox with words will auto close after 5 min (300 sec.)
Slight improvement as discussed in #1065
=> gui: Wallet -> Get my words, auto close.

src/validation.cpp
Manual backport of https://github.com/bitcoin/bitcoin/commit/0e7c52dc6cbb8fd881a0dd57a6167a812fe71dc4
Fixes issue #1087
Commit message by author sdaftuar:
The call to CheckBlock() in ConnectBlock() is redundant with calls to it
prior to storing a block on disk. If CheckBlock() fails with an error
indicating the block is potentially corrupted, then shut down
immediately, as this is an indication that the node is experiencing
hardware issues.  (If we didn't shut down, we could go into an infinite
loop trying to reconnect this same bad block, as we're not setting the
block's status to FAILED in the case where there is potential
corruption.)
If CheckBlock() fails for some other reason, we'll end up flagging this
block as bad (perhaps some prior software version "let a bad block in",
as the …
=> backport: Shut down if trying to connect a corrupted block

src/qt/assetsdialog.cpp, src/qt/createassetdialog.cpp, src/qt/reissueassetdialog.cpp, src/qt/restrictedassetsdialog.cpp, src/qt/sendcoinsdialog.cpp
The window confirming the fee that will be added to a transaction has the fee amount in dark red. While this looks good in light mode, it is hard to see in dark mode. Changed the color of the fee amount from \#aa0000 to \#e82121.
Fixes #1072
=> GUI: Change non-ideal color for dark mode on "added to transaction" window

src/qt/forms/mnemonicdialog2.ui, src/qt/forms/mnemonicdialog3.ui
* Re-word in the import dialog.
* Passphrase is used multiple times, renaming this to Seed Extension Word.
* Add better tooltip.
Co-authored-by: kinkajou
Co-authored-by: LSJI07
Co-authored-by: Hraf
=> gui: optional seed extension word rename

src/qt/assetfilterproxy.cpp, src/qt/assetfilterproxy.h, src/qt/overviewpage.cpp
* AssetFilterProxy expanded to be able to search
for strings in the whole asset name.
Previously only the prefix was searchable.
=> gui: search for string in whole asset name.

src/qt/ravengui.cpp
Remove 'main/sub/unique' from the tooltip.
The list was incomplete, and adding everything would make it too long.
=> gui: Create Assets tooltip wording

src/validation.cpp
Manual backport of bitcoin PR 15305
If we're unable to disconnect a block during normal operation, then that is a
failure of our local system (such as disk failure) or the chain that we are on
(eg CVE-2018-17144), but cannot be due to failure of the (more work) chain that
we're trying to validate.
We should abort rather than stay on a less work chain.
NOTE: test in later PR, requires some refactoring or updating of the test_framework.
=> backport: [validation] Crash if disconnecting a block fails

src/net.cpp, src/net.h
Manual backport of bitcoin PR #17906
Initialize CConnman byte counters during construction, so GetTotalBytesRecv()
and GetTotalBytesSent() methods don't return garbage before Start() is called.
Change shouldn't have any effect outside of the GUI. It just fixes a race
condition during a qt test that was observed on travis:
https://travis-ci.org/bitcoin/bitcoin/jobs/634989685
=> backport: gui: Set CConnman byte counters earlier to avoid uninitialized reads

src/rpc/server.cpp
manual backport of bitcoin PR # 14993
rpc: Fix data race (UB) in InterruptRPC()
=> backport: rpc: Fix data race (UB) in InterruptRPC()

src/netaddress.cpp, src/netaddress.h
Manual backport of bitcoin PR 14728
Reachable from either place where SetIP is used when our best-guess
addrLocal for a peer is IPv4, but the peer tells us it's reaching us at
an IPv6 address.
In that case, SetIP turns an IPv4 address into an IPv6 address without
setting the scopeId, which is subsequently read in GetSockAddr during
CNetAddr::ToStringIP and passed to getnameinfo. Fix by ensuring every
constructor initializes the scopeId field with something.
=> backport: fix uninitialized read when stringifying an addrLocal

src/net.h, src/net_processing.cpp
Manual backport of bitcoin PR #13907
The largest sensible size for a locator is log in the number of blocks.
But, as noted by Coinr8d on BCT a maximum size message could encode a
hundred thousand locators.  If height were used to limit the messages
that could open new attacks where peers on long low diff forks would
get disconnected and end up stuck.
Ideally, nodes first first learn to limit the size of locators they
send before limiting what would be processed, but common implementations
back off with an exponent of 2 and have an implicit limit of 2^32
blocks, so they already cannot produce locators over some size.
This sets the limit to an absurdly high amount of 101 in order to
maximize compatibility with existing software.
=> backport: Introduce a maximum size for locators.

src/qt/walletmodeltransaction.cpp, src/qt/walletmodeltransaction.h
Backport of bitcoin PR #10920
https://github.com/bitcoin/bitcoin/pull/10920
=> backport: [qt] Fix potential memory leak in newPossibleKey(ChangeCWallet *wallet) (bitcoin #10920)

src/wallet/wallet.cpp
Original-author: promag
This PR fixes a race for setLockedCoins when lockUnspents is true. For instance, it should not be possible to use the same unspent in concurrent fundrawtransaction calls.
Now the cs_main and cs_wallet locks are held during CreateTransaction and LockCoin(s). Also added some style nits around the change.
=> backport: Make CWallet::FundTransaction atomic (bitcoin #11864)

src/qt/addresstablemodel.cpp
* SetAddressBook(...) is locking cs_wallet internally
* DelAddressBook(...) is locking cs_wallet internally
=> backport: Remove redundant locks (bitcoin #11733)

src/qt/createassetdialog.cpp, src/qt/createassetdialog.h, src/qt/forms/createassetdialog.ui, src/qt/forms/reissueassetdialog.ui, src/qt/reissueassetdialog.cpp, src/qt/reissueassetdialog.h
* Add button to open ipfs-hash in the configured ipfs-viewer.
This can be handy to verify your ipfs-hash is correct, before creating the asset.
* Remove a check that enabled the Check Availability button once the `Add IPFS/Txid hash` was enabled.
=> gui: create and reissue asset views - browse ipfs button

src/validation.cpp
Reverts RavenProject/Ravencoin#1126
Reverted at Tron's request.
Need to review whether PR#1159 should be reverted by the same logic.
=> Revert "backport: Shut down if trying to connect a corrupted block"

src/validation.cpp
This bug was discovered in Dec-2021 on mainnet when two blocks were mined within one second. Pool operators locked up and required restarting. 
It happened because when CheckTxInputs finds a double spend, ConnectBlock fails but does not mark the bad transaction to be flushed from the mempool.
It is described in detail in Issue [#1183](https://github.com/RavenProject/Ravencoin/issues/1183) which this PR fixes.
Thanks go to Jeremy for help with this bug.
=> Fix mining bug - lockup in CreateNewBlock loop

README.md
It seems many users don't know what to do when accessing the Ravencoin repo. This is a trivial commit. Should I create some sort of how-to index file linking to respective md files in docs?
=> Put the how-to md files front and center for novice users

test/functional/test_framework/util.py
The "-acceptnonstdtxn" CLI option on raven-v4.3.2.1 is broken (it never has any effect). A previous PR fixed it so that it now behaves similarly to the behavior on bitcoin. But 5 functional tests assumed that regtest would by default accept non-standard transactions, and therefore broke. This PR just tells the functional test framework to use the "-acceptnonstdtxn" option, which fixes the fails.
=> Fix function test failures which depend on nonstandard transactions
