RavenProject/Ravencoin

- src/miner.h
- src/txmempool.h
Applying the patch from this bitcoin PR fixed my mac build:
https://github.com/bitcoin/bitcoin/pull/12032
> Fixing darwin build

- src/assets/assets.cpp
> Issue #87 Fix typo in UndoAssetCoin error statement

- src/Makefile.test.include
- src/assets/assets.cpp
- src/assets/assets.h
- src/assets/assettypes.h
- src/coins.cpp
- src/coins.h
- src/consensus/tx_verify.cpp
- src/primitives/transaction.h
- src/rpc/assets.cpp
- src/rpc/client.cpp
- src/script/ismine.cpp
- src/script/script.cpp
- src/script/script.h
- src/script/sign.cpp
- src/script/standard.cpp
- src/script/standard.h
- src/test/assets/asset_reissue_tests.cpp
- src/undo.h
- src/validation.cpp
- src/validation.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
This completes part of the Phase 2 requirements that allow the ability to reissue assets.
> Add Reissue of assets

- src/rpc/assets.cpp
- test/functional/assets.py
sample output:
```help transfer
transfer "asset_name" qty "to_address"
THIS COMMAND IS NOT YET ACTIVE!
https://github.com/RavenProject/rips/blob/master/rip-0002.mediawiki
Transfers a quantity of an owned asset to a given address
Arguments:
...```
> BIP-9/RIP-2 related bugfixes

- src/rpc/misc.cpp
- src/validation.cpp
- test/functional/raven_cli.py
Supersedes #118 
- This just fixes some minor typos in the codebase
> minor typos

- src/assets/assets.cpp
- test/functional/listmyassets.py
- test/functional/test_framework/util.py
- test/functional/test_runner.py
(even if zero balance is still cached).
> GetMyAssetBalances() no longer returns zero balances 

- doc/README.md
Completed howto for running binaries on CentOS 7, verified 2018-05-22
> Update README.md - Verified howto for CentOS 7

- src/assets/assetdb.cpp
- src/script/script.cpp
* boost wasn't being included properly to satisfy mingw
* unused imports were causing linkage problems
> Fixes windows build problems

- src/rpc/assets.cpp
- test/functional/rawassettransactions.py
- test/functional/test_framework/mininode.py
- test/functional/test_runner.py
Verifies that scriptSig tampering voids transfer.
Changed listmyassets output: "index"(string) to "vout"(int).
> Functional test for issue and transfer of assets via raw transactions.

- src/pow.cpp
Proposal to move to Dark Gravity Wave for pow difficulty readjustment.  Will activate at the same time as assets (RIP-2).
> Moving to DGW when RIP-2 is activated.

- src/assets/assets.cpp
- src/assets/assets.h
- src/test/assets/asset_tests.cpp
> Under channel namespace fix

- whitepaper/README.md
This pull request to for cherry-picking a couple commits that changed the text in the readme.md. 
This commits were made by user  UsertJonPizza.
> Typo fixes made by  UsertJonPizza

- src/assets/assets.cpp
- src/wallet/wallet.cpp
- test/functional/assets.py
This PR fixes bug #210 
A database error was occurring where only asset spends that you owned where be subtracted from the database. This made it so the rpc calls which listed asset balances where listing incorrect balances. This fixes the issue so all nodes should return the correct balances.
> Fix for bug 210

- src/validation.cpp
> Fix reindex segfault when using build from ubuntu 18.04

- assets/tools/issuebulk.py
- assets/tools/signed_promises.py
python scripts should invoke the python interpreter. hopefully these are written in python3, if not adjust.
> invoke python interpreter

- src/assets/assets.h
Fix to the pull request #264 made by @bedri
> Fix compile warnings on linux 

- assets/tools/blockfacts.py
- src/assets/assets.cpp
Allows an additional character for assets that don't require an owner token.
> Tron fix asset len - add utility script

- src/assets/assets.cpp
This is a consensus change which will require a testnet restart.
> Allow reissue with amount of 0

- src/Makefile.am
- src/assets/assettypes.cpp
- src/assets/assettypes.h
- src/consensus/consensus.cpp
- src/consensus/consensus.h
- src/rpc/protocol.cpp
- src/script/script.cpp
- src/script/script.h
- src/wallet/wallet.h
When PR #293 . Linux stopped building. This fixes the linux errors that were introduced with PR #293
> Fix linux build errors

- src/rpc/assets.cpp
> Update rpc examples to have valid asset names

- src/qt/overviewpage.cpp
Provides a status of block count until vote starts.
> Add status of blocks before vote

- src/qt/sendassetsentry.cpp
Sometime when clicking the Send Administrator asset checkbox. The list of asset wouldn't update. 
This should fix that issue.
> Try to fix, admin assets not showing up

- src/qt/transactionrecord.cpp
Before, when your wallet was sent an asset from another user. There would be two entries added into the transaction list. 
- Asset transaction
- RVN transaction with the amount of zero. 
This change makes it so the RVN transaction of zero doesn't get added to the list of transactions. This makes the transaction list look much nicer as it only contains transactions that impact your balances
This also adds a change where when calculating the details for the transaction, if it is a Asset Transaction it will be skipped by the RVN transaction details, should save some time when looping through Tx that have lots of TxOut which contain asset scripts.
> Remove 0 amount transaction from wallet transaction list

- src/wallet/rpcwallet.cpp
- Left over failure from when RBF was hidden from the GUI and RPC in  #349
> Fix linux build issue

- src/assets/assets.cpp
- src/consensus/tx_verify.cpp
- src/primitives/transaction.h
- src/validation.cpp
- test/functional/feature_rawassettransactions.py
- This is in response to the #390 which allow some transactions into the mempool that were invalid. 
- This made it so blocks produced by miners were invalid
- This fix makes to so that the validation checks for new transaction into the mempool mimic the checks for Connecting the block
> Fix Vuln #390

- src/rpc/assets.cpp
really did wish that it did sort the return via blockheight though :)
> Minor fixes in rpc help

- src/blockencodings.cpp
- src/blockencodings.h
- src/net.cpp
- src/net.h
- src/net_processing.cpp
- src/protocol.cpp
- src/protocol.h
- src/validationinterface.cpp
- src/version.h
- Add getassetdata network request
- Return the asset meta data including the block height and block hash of the recent issue/reissued data
> Add a getassetdata network request 

- src/qt/locale/raven_de.ts
changed some words to keep translation more consistent
edited spelling mistakes
suggested alternative translations
> [Translation] Update raven_de.ts

- src/assets/assets.h
- src/blockencodings.cpp
- src/blockencodings.h
- src/chainparams.cpp
- src/net.cpp
- src/net.h
- src/net_processing.cpp
- src/protocol.cpp
- src/protocol.h
- src/rpc/net.cpp
- src/version.h
- Update the getassetdata network request to better handle 
- When assets aren't found
- The return metadata from that asset
> Update getassetdata network request

- doc/release-notes/release-notes-2.2.2.md
Fixes #505 
New release notes file for version 2.2.2
> Adding release notes for v2.2.2 release

- src/rpc/assets.cpp
- src/validation.cpp
- src/validation.h
- src/wallet/wallet.h
- Adding a couple changes that should of made it into 2.2.2
- Nothing critical has changed in this PR
> Update develop with renames, and fixes

- test/functional/mempool_limit.py
- test/functional/p2p_feefilter.py
- test/functional/rpc_fundrawtransaction.py
- test/functional/wallet_abandonconflict.py
The fees were changes in PR #523  which caused several tests to fail. This commit updates the tests to match the new fees.
> Fix functional tests from pr 523

- src/assets/assets.cpp
> Fix issueunique on sub assets

- test/functional/feature_assets.py
- test/functional/feature_dbcrash.py
- test/functional/feature_rawassettransactions.py
This should take care of the remaining functional tests that were failing due to the recent increase in min tx fee.  There are still some functional tests failing from some of the recent messaging changes, looking into those next.
> Fixing funtional tests that were failing due to new fee changes

- test/functional/p2p_feefilter.py
Small change to fix the fee filter functional test.  The min fee was raised from zero causing this test to fail, now all of the minimums are above the min tx fee.
> Fixes the p2p_feefilter functional test

- src/init.cpp
Fixes a small error that caused the RPC_bind.py functional test to fail.
> Fixes the rpc_bind.py functional test

- README.md
> Remove mailing list link

- src/assets/assets.cpp
- src/consensus/tx_verify.cpp
- src/validation.cpp
- Fix section where testnet stopped syncing on block 38499
> update messaging sync

- test/functional/feature_messaging.py
- test/functional/test_runner.py
Let me know if you see any use cases that aren't represented!
> Some functional tests for messaging feature.

- src/validation.cpp
> Fix height check

- src/init.cpp
- src/net.cpp
- src/net.h
- src/net_processing.cpp
- src/net_processing.h
- src/test/test_raven.cpp
- src/validation.cpp
- src/validation.h
- Ravencoin already had some of the changes the 0.15.1 added to bitcoin, however there were some changes that we didn't have. This should add those changes. 
- In order to save time and get bug fixes added to the code base, we will be backporting the testing changes at a later time.
> [Backport] 0.15.1 backport critical change(no tests) to ravencoin

- src/assets/assets.cpp
- src/assets/assets.h
- src/chainparams.cpp
- src/chainparams.h
- src/chainparamsbase.cpp
- src/consensus/consensus.h
- src/consensus/params.h
- src/consensus/tx_verify.cpp
- src/consensus/tx_verify.h
- src/net_processing.cpp
- src/primitives/transaction.h
- src/qt/reissueassetdialog.cpp
- src/qt/sendassetsentry.cpp
- src/rpc/assets.cpp
- src/rpc/blockchain.cpp
- src/rpc/messages.cpp
- src/validation.cpp
- src/validation.h
- src/version.h
- src/versionbits.cpp
- src/versionbits.h
- src/wallet/fees.cpp
- src/wallet/wallet.cpp
> Update for testnet7 and removal of BIP and fee logic

- src/assets/assets.cpp
- src/qt/createassetdialog.cpp
- src/qt/reissueassetdialog.cpp
- src/rpc/assets.cpp
This fixes #627 fixes #628 fixes #633 fixes #626
> Fix restricted assets bugs

- src/consensus/validation.h
- src/init.cpp
- src/miner.cpp
- src/rpc/blockchain.cpp
- src/validation.cpp
- Add new rpc call `clearmempool`
- Add new daemon flag `-autofixmempool`
> Add extra mempool rpc call, and allow for auto clearing

- src/consensus/tx_verify.cpp
- src/core_write.cpp
- src/rpc/assets.cpp
- src/rpc/messages.cpp
- src/rpc/rawtransaction.cpp
- src/rpc/server.cpp
- src/rpc/server.h
- Updated `decodescript`
- Updated `decoderawtransaction`
> Add message data to decoded scripts

- .github/old-workflows/build-arm32v7-disable_wallet.yml
- .github/old-workflows/build-arm32v7.yml
- .github/old-workflows/build-linux64-disable_wallet.yml
- .github/old-workflows/build-linux64.yml
- .github/old-workflows/build-osx.yml
- .github/scripts/00-install-deps.sh
- .github/scripts/01-update-docker.sh
- .github/scripts/02-copy-build-dependencies.sh
- .github/scripts/03-export-path.sh
- .github/scripts/04-configure-build.sh
- .github/scripts/05-binary-checks.sh
- .github/scripts/06-package.sh
- .github/workflows/build-raven.yml
- .github/workflows/dependencies-arm32v7.yml
- .github/workflows/dependencies-linux.yml
- .github/workflows/dependencies-osx.yml
- .github/workflows/dependencies-windows.yml
This will enable the Ravencoin project repo to utilize githubs actions pipelines for our builds.
> adding github actions workflow

- src/rpc/assets.cpp
- src/txmempool.cpp
- src/txmempool.h
- src/validation.cpp
- src/wallet/rpcwallet.cpp
- Add asset data to listsinceblock rpc call
- Update restricted asset global freeze and unfreeze mempool handling
> Fix restricted freeze unfreeze mempool, update rpc call

- src/assets/rewards.cpp
- src/qt/paymentserver.cpp
A few new build warnings were added recently, this removes those warnings from the build process.
> Fixing new build warnings

- src/wallet/rpcwallet.cpp
- Add watchonly data to listsinceblock returned data
> Add watchonly flag to listsinceblock asset data

- src/qt/ravengui.cpp
- src/qt/ravengui.h
- src/ui_interface.h
- src/version.h
- Added Model that will pop up and tell the user when launching older software
- Added link to GUI wallet on top right of screen that tells the users they are using older software
> [GUI] Add ability to see when wallet is not running latest released software

- src/httpserver.cpp
I'm not sure how others are doing it, but the only way I can get this to compile is if this include is added.
> Include deque in httpserver.cpp

- src/assets/assets.cpp
- src/chainparams.cpp
- src/consensus/consensus.h
- src/consensus/params.h
- src/net_processing.cpp
- src/rpc/blockchain.cpp
- src/validation.cpp
- src/validation.h
- src/version.h
- src/versionbits.cpp
- src/wallet/walletdb.cpp
> Add transfer script size RIP

- assets/tools/asset_audit.py
Merging to devleop
Closes #804
> Update asset auditor to notify by email

- .github/ISSUE_TEMPLATE.md
Issue template on github updated to say Ravencoin.
> Docs: Issue template on github

- src/qt/darkstyle.cpp
- src/qt/raven.cpp
Set attributes before invoking the application.
This way, they work.
> GUI: Enable High DPI Scaling (PR: #926)

- src/qt/forms/reissueassetdialog.ui
- src/qt/reissueassetdialog.cpp
Manage Assets view.
- Reissue Asset headline.
- Change some wording.
- Resize the combobox.
- Add tooltip to the combobox.
> GUI: Manage Assets - Add label for reissue assets (PR #929).

- .github/ISSUE_TEMPLATE.md
- doc/README.md
- doc/dependencies.md
- doc/developer-notes.md
Update dependencies.md
Change to a working discord invite.
Use the same discord invite everywhere.
Revert urls to bitcoin-core github.
> Doc: Update dependencies.md, discord invites and revert some wrong urls (PR #933).

- src/qt/forms/assetsdialog.ui
- src/qt/forms/sendassetsentry.ui
- src/qt/forms/sendcoinsentry.ui
- When sending RVN we use the word send.
- When transferring assets we use the word transfer.
- We don't pay.
> GUI: Try to use the same words. (Send and Transfer no Pay) (PR #931)

- src/qt/receiverequestdialog.cpp
This was originally committed as PR #869 from Shaveyy on 22.01.2021 but the pull request source was since deleted. Thus re-creating here.
> GUI: Add preview to QR code drag and drop (PR #938)

- src/qt/guiconstants.h
- src/qt/optionsdialog.cpp
- src/qt/optionsmodel.cpp
Moves third party explorer urls and default ipfs-viewer to guiconstants.h
Should fix #932
> Cleanups: Move urls to defines.

- contrib/install_db4.sh
This script automates the process of downloading and compiling Berkeley DB 4.8.
Rebranded to Ravencoin
> Contrib: Copy install_db4.sh from bitcoin (PR #934).

- .github/scripts/00-install-deps.sh
- .github/scripts/02-copy-build-dependencies.sh
- .github/scripts/03-export-path.sh
- .github/scripts/04-configure-build.sh
- .github/scripts/05-binary-checks.sh
- .github/scripts/06-package.sh
- .github/workflows/build-raven.yml
- depends/packages/packages.mk
- depends/packages/qt.mk
- This adds aarch64 to the auto-builds.
Requires #954 to be merged, and needs a rebase.
Will fail to build without.
> Build: Add aarch64-linux-gnu

- doc/build-ubuntu.md
Detailed step-by-step instructions on how to build
from git on Ubuntu 21.04 Hirsute Hippo.
Depends on #934 to work.
> Doc: Add build-ubuntu.md (PR #935)

- doc/build-ubuntu.md
- Added Ubuntu 18.04 dependencies
- Fixed an issue with quotation marks
> Update to build-ubuntu.md (PR #964)

- src/qt/paymentrequest.proto
- src/qt/ravenunits.h
- src/rpc/mining.cpp
Thanks to Atlantys#0001 at Discord for finding.
> fix: broken links due to search and replace (PR #1000).

- src/crypto/ethash/lib/ethash/endianness.hpp
- src/crypto/ethash/lib/keccak/keccak.c
build: ethash endian include freebsd.
build: keccack endian include freebsd.
> build: fix includes for freebsd (PR #999).

- configure.ac
> build: Suppress -Wdeprecated-copy warnings

- src/qt/transactionview.cpp
> fdov-backport-btc9683

- src/txdb.cpp
> refactor: remove unneccesary parantheses.

- src/validation.cpp
We don't want these to change.
Fixes issue #800.
> verification.cpp update variables to be const

- src/qt/forms/modaloverlay.ui
- src/qt/modaloverlay.cpp
Add version with commit hash.
Easier to help people with sync issues.
> gui: add version to modal overlay

- src/qt/raven.cpp
moved app out of the if.
removed extra qt version check.
> Move app out of if, and remove qt version checks

- share/qt/Info.plist.in
> gui: osx darkmode

- src/qt/reissueassetdialog.cpp
Update asset list when the qcombobox is shown.
Fixes #1059
> gui: Manage assets - update list when shown.

- depends/packages/zeromq.mk
> depends: zeromq 4.3.4

- src/net_processing.cpp
- src/qt/guiconstants.h
- src/qt/transactiondesc.cpp
- src/qt/transactionrecord.cpp
- src/qt/transactionrecord.h
- src/qt/transactiontablemodel.cpp
- src/validationinterface.cpp
- src/validationinterface.h
- src/wallet/wallet.cpp
- src/wallet/wallet.h
Manual backport of https://github.com/bitcoin/bitcoin/commit/beef7ec4be725beea870a2da510d2817487601ec
Fixes issue #1114
CVE-2018-17145
> Remove useless mapRequest tracking

- src/wallet/wallet.cpp
- src/wallet/wallet.h
This PR resolves issued described here https://github.com/RavenProject/Ravencoin/issues/1088.
> Add asset support for IsFromMe

- src/wallet/bip39.cpp
> fix: include array to fix building for osx.

- src/qt/forms/assetsdialog.ui
- src/qt/forms/createassetdialog.ui
- src/qt/forms/overviewpage.ui
- src/qt/forms/reissueassetdialog.ui
- src/qt/forms/restrictedassetsdialog.ui
- src/qt/forms/sendcoinsdialog.ui
- src/qt/raven.cpp
* Increase minimum window size to 1024x700
* Adjust layouts most pages, to be usable at the new minimum window size.
* Most margins are reduced.
> gui: minimum sizes and margins

- src/wallet/wallet.h
Manual backport of bitcoin PR #16572
> backport: wallet: Fix Char as Bool in Wallet

- src/rpc/rawtransaction.cpp
Fixes issue #1102.
Removed some brackets.
Removed one asset_quantity.
Adjusted indentation.
> Fix createrawtransaction transferwithmessage RPC

- src/assets/assets.cpp
- Fix bug in memory check
- Use .at instead of [] checking as this is the correct way to access memory in a map
- rename temp object
This fixes an issue currently happening on testnet. 
Nodes are getting stuck when trying to validate block 1127354.
@hans-schmidt should be able to verify
> Fix bug with in memory qualifier address checking
